// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts,import_extension=none"
// @generated from file auth/auth_service.proto (package auth, syntax proto3)
/* eslint-disable */

import { AuthService } from "./auth_service_pb";

/**
 * @generated from rpc auth.AuthService.Register
 */
export const register = AuthService.method.register;

/**
 * @generated from rpc auth.AuthService.Login
 */
export const login = AuthService.method.login;

/**
 * @generated from rpc auth.AuthService.Logout
 */
export const logout = AuthService.method.logout;

/**
 * @generated from rpc auth.AuthService.RefreshToken
 */
export const refreshToken = AuthService.method.refreshToken;
