// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file auth/auth.proto (package auth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/auth.proto.
 */
export const file_auth_auth: GenFile = /*@__PURE__*/
  fileDesc("Cg9hdXRoL2F1dGgucHJvdG8SBGF1dGgiaAoJVG9rZW5QYWlyEhQKDGFjY2Vzc190b2tlbhgBIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAIgASgJEi4KCmV4cGlyZXNfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQmcKCGNvbS5hdXRoQglBdXRoUHJvdG9QAVogZ3JwYy1zZXJ2ZXIvcHJvdG8tZ2VuZXJhdGVkL2F1dGiiAgNBWFiqAgRBdXRoygIEQXV0aOICEEF1dGhcR1BCTWV0YWRhdGHqAgRBdXRoYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * TokenPair represents a pair of tokens issued for authentication.
 *
 * @generated from message auth.TokenPair
 */
export type TokenPair = Message<"auth.TokenPair"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;
};

/**
 * Describes the message auth.TokenPair.
 * Use `create(TokenPairSchema)` to create a new message.
 */
export const TokenPairSchema: GenMessage<TokenPair> = /*@__PURE__*/
  messageDesc(file_auth_auth, 0);

