// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file auth/auth_service.proto (package auth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "../user/user_pb";
import { file_user_user } from "../user/user_pb";
import type { TokenPair } from "./auth_pb";
import { file_auth_auth } from "./auth_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/auth_service.proto.
 */
export const file_auth_auth_service: GenFile = /*@__PURE__*/
  fileDesc("ChdhdXRoL2F1dGhfc2VydmljZS5wcm90bxIEYXV0aCJACg9SZWdpc3RlclJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkSDAoEbmFtZRgDIAEoCSJNChBSZWdpc3RlclJlc3BvbnNlEhgKBHVzZXIYASABKAsyCi51c2VyLlVzZXISHwoGdG9rZW5zGAIgASgLMg8uYXV0aC5Ub2tlblBhaXIiLwoMTG9naW5SZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIkoKDUxvZ2luUmVzcG9uc2USGAoEdXNlchgBIAEoCzIKLnVzZXIuVXNlchIfCgZ0b2tlbnMYAiABKAsyDy5hdXRoLlRva2VuUGFpciIsChNSZWZyZXNoVG9rZW5SZXF1ZXN0EhUKDXJlZnJlc2hfdG9rZW4YASABKAkiNwoUUmVmcmVzaFRva2VuUmVzcG9uc2USHwoGdG9rZW5zGAEgASgLMg8uYXV0aC5Ub2tlblBhaXIiJQoNTG9nb3V0UmVxdWVzdBIUCgxhY2Nlc3NfdG9rZW4YASABKAkiEAoOTG9nb3V0UmVzcG9uc2Uy/gEKC0F1dGhTZXJ2aWNlEjsKCFJlZ2lzdGVyEhUuYXV0aC5SZWdpc3RlclJlcXVlc3QaFi5hdXRoLlJlZ2lzdGVyUmVzcG9uc2UiABIyCgVMb2dpbhISLmF1dGguTG9naW5SZXF1ZXN0GhMuYXV0aC5Mb2dpblJlc3BvbnNlIgASNQoGTG9nb3V0EhMuYXV0aC5Mb2dvdXRSZXF1ZXN0GhQuYXV0aC5Mb2dvdXRSZXNwb25zZSIAEkcKDFJlZnJlc2hUb2tlbhIZLmF1dGguUmVmcmVzaFRva2VuUmVxdWVzdBoaLmF1dGguUmVmcmVzaFRva2VuUmVzcG9uc2UiAEJuCghjb20uYXV0aEIQQXV0aFNlcnZpY2VQcm90b1ABWiBncnBjLXNlcnZlci9wcm90by1nZW5lcmF0ZWQvYXV0aKICA0FYWKoCBEF1dGjKAgRBdXRo4gIQQXV0aFxHUEJNZXRhZGF0YeoCBEF1dGhiBnByb3RvMw", [file_user_user, file_auth_auth]);

/**
 * @generated from message auth.RegisterRequest
 */
export type RegisterRequest = Message<"auth.RegisterRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message auth.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_auth_auth_service, 0);

/**
 * @generated from message auth.RegisterResponse
 */
export type RegisterResponse = Message<"auth.RegisterResponse"> & {
  /**
   * @generated from field: user.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: auth.TokenPair tokens = 2;
   */
  tokens?: TokenPair;
};

/**
 * Describes the message auth.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_auth_auth_service, 1);

/**
 * @generated from message auth.LoginRequest
 */
export type LoginRequest = Message<"auth.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_auth_auth_service, 2);

/**
 * @generated from message auth.LoginResponse
 */
export type LoginResponse = Message<"auth.LoginResponse"> & {
  /**
   * @generated from field: user.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: auth.TokenPair tokens = 2;
   */
  tokens?: TokenPair;
};

/**
 * Describes the message auth.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_auth_auth_service, 3);

/**
 * @generated from message auth.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"auth.RefreshTokenRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_auth_auth_service, 4);

/**
 * @generated from message auth.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"auth.RefreshTokenResponse"> & {
  /**
   * @generated from field: auth.TokenPair tokens = 1;
   */
  tokens?: TokenPair;
};

/**
 * Describes the message auth.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/
  messageDesc(file_auth_auth_service, 5);

/**
 * @generated from message auth.LogoutRequest
 */
export type LogoutRequest = Message<"auth.LogoutRequest"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;
};

/**
 * Describes the message auth.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_auth_auth_service, 6);

/**
 * @generated from message auth.LogoutResponse
 */
export type LogoutResponse = Message<"auth.LogoutResponse"> & {
};

/**
 * Describes the message auth.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_auth_auth_service, 7);

/**
 * @generated from service auth.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_auth_service, 0);

