// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: item/v1/item_service.proto

package itemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_item_v1_item_service_proto protoreflect.FileDescriptor

const file_item_v1_item_service_proto_rawDesc = "" +
	"\n" +
	"\x1aitem/v1/item_service.proto\x12\aitem.v1\x1a\x12item/v1/item.proto2\xb9\x03\n" +
	"\vItemService\x12G\n" +
	"\n" +
	"CreateItem\x12\x1a.item.v1.CreateItemRequest\x1a\x1b.item.v1.CreateItemResponse\"\x00\x12>\n" +
	"\aGetItem\x12\x17.item.v1.GetItemRequest\x1a\x18.item.v1.GetItemResponse\"\x00\x12D\n" +
	"\tListItems\x12\x19.item.v1.ListItemsRequest\x1a\x1a.item.v1.ListItemsResponse\"\x00\x12G\n" +
	"\n" +
	"UpdateItem\x12\x1a.item.v1.UpdateItemRequest\x1a\x1b.item.v1.UpdateItemResponse\"\x00\x12G\n" +
	"\n" +
	"DeleteItem\x12\x1a.item.v1.DeleteItemRequest\x1a\x1b.item.v1.DeleteItemResponse\"\x00\x12I\n" +
	"\n" +
	"WatchItems\x12\x1a.item.v1.WatchItemsRequest\x1a\x1b.item.v1.WatchItemsResponse\"\x000\x01B\x9e\x01\n" +
	"\vcom.item.v1B\x10ItemServiceProtoP\x01Z@github.com/heojeongbo/grpc/server/proto-generated/item/v1;itemv1\xa2\x02\x03IXX\xaa\x02\aItem.V1\xca\x02\aItem\\V1\xe2\x02\x13Item\\V1\\GPBMetadata\xea\x02\bItem::V1b\x06proto3"

var file_item_v1_item_service_proto_goTypes = []any{
	(*CreateItemRequest)(nil),  // 0: item.v1.CreateItemRequest
	(*GetItemRequest)(nil),     // 1: item.v1.GetItemRequest
	(*ListItemsRequest)(nil),   // 2: item.v1.ListItemsRequest
	(*UpdateItemRequest)(nil),  // 3: item.v1.UpdateItemRequest
	(*DeleteItemRequest)(nil),  // 4: item.v1.DeleteItemRequest
	(*WatchItemsRequest)(nil),  // 5: item.v1.WatchItemsRequest
	(*CreateItemResponse)(nil), // 6: item.v1.CreateItemResponse
	(*GetItemResponse)(nil),    // 7: item.v1.GetItemResponse
	(*ListItemsResponse)(nil),  // 8: item.v1.ListItemsResponse
	(*UpdateItemResponse)(nil), // 9: item.v1.UpdateItemResponse
	(*DeleteItemResponse)(nil), // 10: item.v1.DeleteItemResponse
	(*WatchItemsResponse)(nil), // 11: item.v1.WatchItemsResponse
}
var file_item_v1_item_service_proto_depIdxs = []int32{
	0,  // 0: item.v1.ItemService.CreateItem:input_type -> item.v1.CreateItemRequest
	1,  // 1: item.v1.ItemService.GetItem:input_type -> item.v1.GetItemRequest
	2,  // 2: item.v1.ItemService.ListItems:input_type -> item.v1.ListItemsRequest
	3,  // 3: item.v1.ItemService.UpdateItem:input_type -> item.v1.UpdateItemRequest
	4,  // 4: item.v1.ItemService.DeleteItem:input_type -> item.v1.DeleteItemRequest
	5,  // 5: item.v1.ItemService.WatchItems:input_type -> item.v1.WatchItemsRequest
	6,  // 6: item.v1.ItemService.CreateItem:output_type -> item.v1.CreateItemResponse
	7,  // 7: item.v1.ItemService.GetItem:output_type -> item.v1.GetItemResponse
	8,  // 8: item.v1.ItemService.ListItems:output_type -> item.v1.ListItemsResponse
	9,  // 9: item.v1.ItemService.UpdateItem:output_type -> item.v1.UpdateItemResponse
	10, // 10: item.v1.ItemService.DeleteItem:output_type -> item.v1.DeleteItemResponse
	11, // 11: item.v1.ItemService.WatchItems:output_type -> item.v1.WatchItemsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_item_v1_item_service_proto_init() }
func file_item_v1_item_service_proto_init() {
	if File_item_v1_item_service_proto != nil {
		return
	}
	file_item_v1_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_v1_item_service_proto_rawDesc), len(file_item_v1_item_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_v1_item_service_proto_goTypes,
		DependencyIndexes: file_item_v1_item_service_proto_depIdxs,
	}.Build()
	File_item_v1_item_service_proto = out.File
	file_item_v1_item_service_proto_goTypes = nil
	file_item_v1_item_service_proto_depIdxs = nil
}
