// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file user/user.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/user.proto.
 */
export const file_user_user: GenFile = /*@__PURE__*/
  fileDesc("Cg91c2VyL3VzZXIucHJvdG8SBHVzZXIijwEKBFVzZXISCgoCaWQYASABKAkSDQoFZW1haWwYAiABKAkSDAoEbmFtZRgDIAEoCRIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEJnCghjb20udXNlckIJVXNlclByb3RvUAFaIGdycGMtc2VydmVyL3Byb3RvLWdlbmVyYXRlZC91c2VyogIDVVhYqgIEVXNlcsoCBFVzZXLiAhBVc2VyXEdQQk1ldGFkYXRh6gIEVXNlcmIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message user.User
 */
export type User = Message<"user.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message user.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user_user, 0);

