// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file user/user_service.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "./user_pb";
import { file_user_user } from "./user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/user_service.proto.
 */
export const file_user_user_service: GenFile = /*@__PURE__*/
  fileDesc("Chd1c2VyL3VzZXJfc2VydmljZS5wcm90bxIEdXNlciIcCg5HZXRVc2VyUmVxdWVzdBIKCgJpZBgBIAEoCSIrCg9HZXRVc2VyUmVzcG9uc2USGAoEdXNlchgBIAEoCzIKLnVzZXIuVXNlciJZChFVcGRhdGVVc2VyUmVxdWVzdBIKCgJpZBgBIAEoCRIRCgRuYW1lGAIgASgJSACIAQESEgoFZW1haWwYAyABKAlIAYgBAUIHCgVfbmFtZUIICgZfZW1haWwiLgoSVXBkYXRlVXNlclJlc3BvbnNlEhgKBHVzZXIYASABKAsyCi51c2VyLlVzZXIiHwoRRGVsZXRlVXNlclJlcXVlc3QSCgoCaWQYASABKAkiFAoSRGVsZXRlVXNlclJlc3BvbnNlMs0BCgtVc2VyU2VydmljZRI4CgdHZXRVc2VyEhQudXNlci5HZXRVc2VyUmVxdWVzdBoVLnVzZXIuR2V0VXNlclJlc3BvbnNlIgASQQoKVXBkYXRlVXNlchIXLnVzZXIuVXBkYXRlVXNlclJlcXVlc3QaGC51c2VyLlVwZGF0ZVVzZXJSZXNwb25zZSIAEkEKCkRlbGV0ZVVzZXISFy51c2VyLkRlbGV0ZVVzZXJSZXF1ZXN0GhgudXNlci5EZWxldGVVc2VyUmVzcG9uc2UiAEJuCghjb20udXNlckIQVXNlclNlcnZpY2VQcm90b1ABWiBncnBjLXNlcnZlci9wcm90by1nZW5lcmF0ZWQvdXNlcqICA1VYWKoCBFVzZXLKAgRVc2Vy4gIQVXNlclxHUEJNZXRhZGF0YeoCBFVzZXJiBnByb3RvMw", [file_user_user]);

/**
 * @generated from message user.GetUserRequest
 */
export type GetUserRequest = Message<"user.GetUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message user.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_user_user_service, 0);

/**
 * @generated from message user.GetUserResponse
 */
export type GetUserResponse = Message<"user.GetUserResponse"> & {
  /**
   * @generated from field: user.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_user_user_service, 1);

/**
 * @generated from message user.UpdateUserRequest
 */
export type UpdateUserRequest = Message<"user.UpdateUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string email = 3;
   */
  email?: string;
};

/**
 * Describes the message user.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema: GenMessage<UpdateUserRequest> = /*@__PURE__*/
  messageDesc(file_user_user_service, 2);

/**
 * @generated from message user.UpdateUserResponse
 */
export type UpdateUserResponse = Message<"user.UpdateUserResponse"> & {
  /**
   * @generated from field: user.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.UpdateUserResponse.
 * Use `create(UpdateUserResponseSchema)` to create a new message.
 */
export const UpdateUserResponseSchema: GenMessage<UpdateUserResponse> = /*@__PURE__*/
  messageDesc(file_user_user_service, 3);

/**
 * @generated from message user.DeleteUserRequest
 */
export type DeleteUserRequest = Message<"user.DeleteUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message user.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export const DeleteUserRequestSchema: GenMessage<DeleteUserRequest> = /*@__PURE__*/
  messageDesc(file_user_user_service, 4);

/**
 * @generated from message user.DeleteUserResponse
 */
export type DeleteUserResponse = Message<"user.DeleteUserResponse"> & {
};

/**
 * Describes the message user.DeleteUserResponse.
 * Use `create(DeleteUserResponseSchema)` to create a new message.
 */
export const DeleteUserResponseSchema: GenMessage<DeleteUserResponse> = /*@__PURE__*/
  messageDesc(file_user_user_service, 5);

/**
 * @generated from service user.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.UpdateUser
   */
  updateUser: {
    methodKind: "unary";
    input: typeof UpdateUserRequestSchema;
    output: typeof UpdateUserResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.DeleteUser
   */
  deleteUser: {
    methodKind: "unary";
    input: typeof DeleteUserRequestSchema;
    output: typeof DeleteUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user_user_service, 0);

