// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts,import_extension=none"
// @generated from file user/user_service.proto (package user, syntax proto3)
/* eslint-disable */

import { UserService } from "./user_service_pb";

/**
 * @generated from rpc user.UserService.GetUser
 */
export const getUser = UserService.method.getUser;

/**
 * @generated from rpc user.UserService.UpdateUser
 */
export const updateUser = UserService.method.updateUser;

/**
 * @generated from rpc user.UserService.DeleteUser
 */
export const deleteUser = UserService.method.deleteUser;
