// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: item/item_service.proto

package itemconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	item "grpc-server/proto-generated/item"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ItemServiceName is the fully-qualified name of the ItemService service.
	ItemServiceName = "item.ItemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ItemServiceCreateItemProcedure is the fully-qualified name of the ItemService's CreateItem RPC.
	ItemServiceCreateItemProcedure = "/item.ItemService/CreateItem"
	// ItemServiceGetItemProcedure is the fully-qualified name of the ItemService's GetItem RPC.
	ItemServiceGetItemProcedure = "/item.ItemService/GetItem"
	// ItemServiceListItemsProcedure is the fully-qualified name of the ItemService's ListItems RPC.
	ItemServiceListItemsProcedure = "/item.ItemService/ListItems"
	// ItemServiceUpdateItemProcedure is the fully-qualified name of the ItemService's UpdateItem RPC.
	ItemServiceUpdateItemProcedure = "/item.ItemService/UpdateItem"
	// ItemServiceDeleteItemProcedure is the fully-qualified name of the ItemService's DeleteItem RPC.
	ItemServiceDeleteItemProcedure = "/item.ItemService/DeleteItem"
	// ItemServiceWatchItemsProcedure is the fully-qualified name of the ItemService's WatchItems RPC.
	ItemServiceWatchItemsProcedure = "/item.ItemService/WatchItems"
)

// ItemServiceClient is a client for the item.ItemService service.
type ItemServiceClient interface {
	CreateItem(context.Context, *connect.Request[item.CreateItemRequest]) (*connect.Response[item.CreateItemResponse], error)
	GetItem(context.Context, *connect.Request[item.GetItemRequest]) (*connect.Response[item.GetItemResponse], error)
	ListItems(context.Context, *connect.Request[item.ListItemsRequest]) (*connect.Response[item.ListItemsResponse], error)
	UpdateItem(context.Context, *connect.Request[item.UpdateItemRequest]) (*connect.Response[item.UpdateItemResponse], error)
	DeleteItem(context.Context, *connect.Request[item.DeleteItemRequest]) (*connect.Response[item.DeleteItemResponse], error)
	WatchItems(context.Context, *connect.Request[item.WatchItemsRequest]) (*connect.ServerStreamForClient[item.WatchItemsResponse], error)
}

// NewItemServiceClient constructs a client for the item.ItemService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewItemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ItemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	itemServiceMethods := item.File_item_item_service_proto.Services().ByName("ItemService").Methods()
	return &itemServiceClient{
		createItem: connect.NewClient[item.CreateItemRequest, item.CreateItemResponse](
			httpClient,
			baseURL+ItemServiceCreateItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("CreateItem")),
			connect.WithClientOptions(opts...),
		),
		getItem: connect.NewClient[item.GetItemRequest, item.GetItemResponse](
			httpClient,
			baseURL+ItemServiceGetItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("GetItem")),
			connect.WithClientOptions(opts...),
		),
		listItems: connect.NewClient[item.ListItemsRequest, item.ListItemsResponse](
			httpClient,
			baseURL+ItemServiceListItemsProcedure,
			connect.WithSchema(itemServiceMethods.ByName("ListItems")),
			connect.WithClientOptions(opts...),
		),
		updateItem: connect.NewClient[item.UpdateItemRequest, item.UpdateItemResponse](
			httpClient,
			baseURL+ItemServiceUpdateItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("UpdateItem")),
			connect.WithClientOptions(opts...),
		),
		deleteItem: connect.NewClient[item.DeleteItemRequest, item.DeleteItemResponse](
			httpClient,
			baseURL+ItemServiceDeleteItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("DeleteItem")),
			connect.WithClientOptions(opts...),
		),
		watchItems: connect.NewClient[item.WatchItemsRequest, item.WatchItemsResponse](
			httpClient,
			baseURL+ItemServiceWatchItemsProcedure,
			connect.WithSchema(itemServiceMethods.ByName("WatchItems")),
			connect.WithClientOptions(opts...),
		),
	}
}

// itemServiceClient implements ItemServiceClient.
type itemServiceClient struct {
	createItem *connect.Client[item.CreateItemRequest, item.CreateItemResponse]
	getItem    *connect.Client[item.GetItemRequest, item.GetItemResponse]
	listItems  *connect.Client[item.ListItemsRequest, item.ListItemsResponse]
	updateItem *connect.Client[item.UpdateItemRequest, item.UpdateItemResponse]
	deleteItem *connect.Client[item.DeleteItemRequest, item.DeleteItemResponse]
	watchItems *connect.Client[item.WatchItemsRequest, item.WatchItemsResponse]
}

// CreateItem calls item.ItemService.CreateItem.
func (c *itemServiceClient) CreateItem(ctx context.Context, req *connect.Request[item.CreateItemRequest]) (*connect.Response[item.CreateItemResponse], error) {
	return c.createItem.CallUnary(ctx, req)
}

// GetItem calls item.ItemService.GetItem.
func (c *itemServiceClient) GetItem(ctx context.Context, req *connect.Request[item.GetItemRequest]) (*connect.Response[item.GetItemResponse], error) {
	return c.getItem.CallUnary(ctx, req)
}

// ListItems calls item.ItemService.ListItems.
func (c *itemServiceClient) ListItems(ctx context.Context, req *connect.Request[item.ListItemsRequest]) (*connect.Response[item.ListItemsResponse], error) {
	return c.listItems.CallUnary(ctx, req)
}

// UpdateItem calls item.ItemService.UpdateItem.
func (c *itemServiceClient) UpdateItem(ctx context.Context, req *connect.Request[item.UpdateItemRequest]) (*connect.Response[item.UpdateItemResponse], error) {
	return c.updateItem.CallUnary(ctx, req)
}

// DeleteItem calls item.ItemService.DeleteItem.
func (c *itemServiceClient) DeleteItem(ctx context.Context, req *connect.Request[item.DeleteItemRequest]) (*connect.Response[item.DeleteItemResponse], error) {
	return c.deleteItem.CallUnary(ctx, req)
}

// WatchItems calls item.ItemService.WatchItems.
func (c *itemServiceClient) WatchItems(ctx context.Context, req *connect.Request[item.WatchItemsRequest]) (*connect.ServerStreamForClient[item.WatchItemsResponse], error) {
	return c.watchItems.CallServerStream(ctx, req)
}

// ItemServiceHandler is an implementation of the item.ItemService service.
type ItemServiceHandler interface {
	CreateItem(context.Context, *connect.Request[item.CreateItemRequest]) (*connect.Response[item.CreateItemResponse], error)
	GetItem(context.Context, *connect.Request[item.GetItemRequest]) (*connect.Response[item.GetItemResponse], error)
	ListItems(context.Context, *connect.Request[item.ListItemsRequest]) (*connect.Response[item.ListItemsResponse], error)
	UpdateItem(context.Context, *connect.Request[item.UpdateItemRequest]) (*connect.Response[item.UpdateItemResponse], error)
	DeleteItem(context.Context, *connect.Request[item.DeleteItemRequest]) (*connect.Response[item.DeleteItemResponse], error)
	WatchItems(context.Context, *connect.Request[item.WatchItemsRequest], *connect.ServerStream[item.WatchItemsResponse]) error
}

// NewItemServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewItemServiceHandler(svc ItemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	itemServiceMethods := item.File_item_item_service_proto.Services().ByName("ItemService").Methods()
	itemServiceCreateItemHandler := connect.NewUnaryHandler(
		ItemServiceCreateItemProcedure,
		svc.CreateItem,
		connect.WithSchema(itemServiceMethods.ByName("CreateItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceGetItemHandler := connect.NewUnaryHandler(
		ItemServiceGetItemProcedure,
		svc.GetItem,
		connect.WithSchema(itemServiceMethods.ByName("GetItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceListItemsHandler := connect.NewUnaryHandler(
		ItemServiceListItemsProcedure,
		svc.ListItems,
		connect.WithSchema(itemServiceMethods.ByName("ListItems")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceUpdateItemHandler := connect.NewUnaryHandler(
		ItemServiceUpdateItemProcedure,
		svc.UpdateItem,
		connect.WithSchema(itemServiceMethods.ByName("UpdateItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceDeleteItemHandler := connect.NewUnaryHandler(
		ItemServiceDeleteItemProcedure,
		svc.DeleteItem,
		connect.WithSchema(itemServiceMethods.ByName("DeleteItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceWatchItemsHandler := connect.NewServerStreamHandler(
		ItemServiceWatchItemsProcedure,
		svc.WatchItems,
		connect.WithSchema(itemServiceMethods.ByName("WatchItems")),
		connect.WithHandlerOptions(opts...),
	)
	return "/item.ItemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ItemServiceCreateItemProcedure:
			itemServiceCreateItemHandler.ServeHTTP(w, r)
		case ItemServiceGetItemProcedure:
			itemServiceGetItemHandler.ServeHTTP(w, r)
		case ItemServiceListItemsProcedure:
			itemServiceListItemsHandler.ServeHTTP(w, r)
		case ItemServiceUpdateItemProcedure:
			itemServiceUpdateItemHandler.ServeHTTP(w, r)
		case ItemServiceDeleteItemProcedure:
			itemServiceDeleteItemHandler.ServeHTTP(w, r)
		case ItemServiceWatchItemsProcedure:
			itemServiceWatchItemsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedItemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedItemServiceHandler struct{}

func (UnimplementedItemServiceHandler) CreateItem(context.Context, *connect.Request[item.CreateItemRequest]) (*connect.Response[item.CreateItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.ItemService.CreateItem is not implemented"))
}

func (UnimplementedItemServiceHandler) GetItem(context.Context, *connect.Request[item.GetItemRequest]) (*connect.Response[item.GetItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.ItemService.GetItem is not implemented"))
}

func (UnimplementedItemServiceHandler) ListItems(context.Context, *connect.Request[item.ListItemsRequest]) (*connect.Response[item.ListItemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.ItemService.ListItems is not implemented"))
}

func (UnimplementedItemServiceHandler) UpdateItem(context.Context, *connect.Request[item.UpdateItemRequest]) (*connect.Response[item.UpdateItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.ItemService.UpdateItem is not implemented"))
}

func (UnimplementedItemServiceHandler) DeleteItem(context.Context, *connect.Request[item.DeleteItemRequest]) (*connect.Response[item.DeleteItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.ItemService.DeleteItem is not implemented"))
}

func (UnimplementedItemServiceHandler) WatchItems(context.Context, *connect.Request[item.WatchItemsRequest], *connect.ServerStream[item.WatchItemsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("item.ItemService.WatchItems is not implemented"))
}
