// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file item/v1/item.proto (package item.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file item/v1/item.proto.
 */
export const file_item_v1_item: GenFile = /*@__PURE__*/
  fileDesc("ChJpdGVtL3YxL2l0ZW0ucHJvdG8SB2l0ZW0udjEilQEKBEl0ZW0SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCI2ChFDcmVhdGVJdGVtUmVxdWVzdBIMCgRuYW1lGAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJIjEKEkNyZWF0ZUl0ZW1SZXNwb25zZRIbCgRpdGVtGAEgASgLMg0uaXRlbS52MS5JdGVtIhwKDkdldEl0ZW1SZXF1ZXN0EgoKAmlkGAEgASgJIi4KD0dldEl0ZW1SZXNwb25zZRIbCgRpdGVtGAEgASgLMg0uaXRlbS52MS5JdGVtIjkKEExpc3RJdGVtc1JlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgFEhIKCnBhZ2VfdG9rZW4YAiABKAkiSgoRTGlzdEl0ZW1zUmVzcG9uc2USHAoFaXRlbXMYASADKAsyDS5pdGVtLnYxLkl0ZW0SFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJIkIKEVVwZGF0ZUl0ZW1SZXF1ZXN0EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkiMQoSVXBkYXRlSXRlbVJlc3BvbnNlEhsKBGl0ZW0YASABKAsyDS5pdGVtLnYxLkl0ZW0iHwoRRGVsZXRlSXRlbVJlcXVlc3QSCgoCaWQYASABKAkiFAoSRGVsZXRlSXRlbVJlc3BvbnNlMu4CCgtJdGVtU2VydmljZRJHCgpDcmVhdGVJdGVtEhouaXRlbS52MS5DcmVhdGVJdGVtUmVxdWVzdBobLml0ZW0udjEuQ3JlYXRlSXRlbVJlc3BvbnNlIgASPgoHR2V0SXRlbRIXLml0ZW0udjEuR2V0SXRlbVJlcXVlc3QaGC5pdGVtLnYxLkdldEl0ZW1SZXNwb25zZSIAEkQKCUxpc3RJdGVtcxIZLml0ZW0udjEuTGlzdEl0ZW1zUmVxdWVzdBoaLml0ZW0udjEuTGlzdEl0ZW1zUmVzcG9uc2UiABJHCgpVcGRhdGVJdGVtEhouaXRlbS52MS5VcGRhdGVJdGVtUmVxdWVzdBobLml0ZW0udjEuVXBkYXRlSXRlbVJlc3BvbnNlIgASRwoKRGVsZXRlSXRlbRIaLml0ZW0udjEuRGVsZXRlSXRlbVJlcXVlc3QaGy5pdGVtLnYxLkRlbGV0ZUl0ZW1SZXNwb25zZSIAQpcBCgtjb20uaXRlbS52MUIJSXRlbVByb3RvUAFaQGdpdGh1Yi5jb20vaGVvamVvbmdiby9ncnBjL3NlcnZlci9wcm90by1nZW5lcmF0ZWQvaXRlbS92MTtpdGVtdjGiAgNJWFiqAgdJdGVtLlYxygIHSXRlbVxWMeICE0l0ZW1cVjFcR1BCTWV0YWRhdGHqAghJdGVtOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Item represents a basic CRUD entity
 *
 * @generated from message item.v1.Item
 */
export type Item = Message<"item.v1.Item"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message item.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema: GenMessage<Item> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 0);

/**
 * CreateItemRequest
 *
 * @generated from message item.v1.CreateItemRequest
 */
export type CreateItemRequest = Message<"item.v1.CreateItemRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message item.v1.CreateItemRequest.
 * Use `create(CreateItemRequestSchema)` to create a new message.
 */
export const CreateItemRequestSchema: GenMessage<CreateItemRequest> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 1);

/**
 * @generated from message item.v1.CreateItemResponse
 */
export type CreateItemResponse = Message<"item.v1.CreateItemResponse"> & {
  /**
   * @generated from field: item.v1.Item item = 1;
   */
  item?: Item;
};

/**
 * Describes the message item.v1.CreateItemResponse.
 * Use `create(CreateItemResponseSchema)` to create a new message.
 */
export const CreateItemResponseSchema: GenMessage<CreateItemResponse> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 2);

/**
 * GetItemRequest
 *
 * @generated from message item.v1.GetItemRequest
 */
export type GetItemRequest = Message<"item.v1.GetItemRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message item.v1.GetItemRequest.
 * Use `create(GetItemRequestSchema)` to create a new message.
 */
export const GetItemRequestSchema: GenMessage<GetItemRequest> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 3);

/**
 * @generated from message item.v1.GetItemResponse
 */
export type GetItemResponse = Message<"item.v1.GetItemResponse"> & {
  /**
   * @generated from field: item.v1.Item item = 1;
   */
  item?: Item;
};

/**
 * Describes the message item.v1.GetItemResponse.
 * Use `create(GetItemResponseSchema)` to create a new message.
 */
export const GetItemResponseSchema: GenMessage<GetItemResponse> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 4);

/**
 * ListItemsRequest
 *
 * @generated from message item.v1.ListItemsRequest
 */
export type ListItemsRequest = Message<"item.v1.ListItemsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message item.v1.ListItemsRequest.
 * Use `create(ListItemsRequestSchema)` to create a new message.
 */
export const ListItemsRequestSchema: GenMessage<ListItemsRequest> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 5);

/**
 * @generated from message item.v1.ListItemsResponse
 */
export type ListItemsResponse = Message<"item.v1.ListItemsResponse"> & {
  /**
   * @generated from field: repeated item.v1.Item items = 1;
   */
  items: Item[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message item.v1.ListItemsResponse.
 * Use `create(ListItemsResponseSchema)` to create a new message.
 */
export const ListItemsResponseSchema: GenMessage<ListItemsResponse> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 6);

/**
 * UpdateItemRequest
 *
 * @generated from message item.v1.UpdateItemRequest
 */
export type UpdateItemRequest = Message<"item.v1.UpdateItemRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Describes the message item.v1.UpdateItemRequest.
 * Use `create(UpdateItemRequestSchema)` to create a new message.
 */
export const UpdateItemRequestSchema: GenMessage<UpdateItemRequest> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 7);

/**
 * @generated from message item.v1.UpdateItemResponse
 */
export type UpdateItemResponse = Message<"item.v1.UpdateItemResponse"> & {
  /**
   * @generated from field: item.v1.Item item = 1;
   */
  item?: Item;
};

/**
 * Describes the message item.v1.UpdateItemResponse.
 * Use `create(UpdateItemResponseSchema)` to create a new message.
 */
export const UpdateItemResponseSchema: GenMessage<UpdateItemResponse> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 8);

/**
 * DeleteItemRequest
 *
 * @generated from message item.v1.DeleteItemRequest
 */
export type DeleteItemRequest = Message<"item.v1.DeleteItemRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message item.v1.DeleteItemRequest.
 * Use `create(DeleteItemRequestSchema)` to create a new message.
 */
export const DeleteItemRequestSchema: GenMessage<DeleteItemRequest> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 9);

/**
 * @generated from message item.v1.DeleteItemResponse
 */
export type DeleteItemResponse = Message<"item.v1.DeleteItemResponse"> & {
};

/**
 * Describes the message item.v1.DeleteItemResponse.
 * Use `create(DeleteItemResponseSchema)` to create a new message.
 */
export const DeleteItemResponseSchema: GenMessage<DeleteItemResponse> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 10);

/**
 * ItemService provides CRUD operations for items
 *
 * @generated from service item.v1.ItemService
 */
export const ItemService: GenService<{
  /**
   * @generated from rpc item.v1.ItemService.CreateItem
   */
  createItem: {
    methodKind: "unary";
    input: typeof CreateItemRequestSchema;
    output: typeof CreateItemResponseSchema;
  },
  /**
   * @generated from rpc item.v1.ItemService.GetItem
   */
  getItem: {
    methodKind: "unary";
    input: typeof GetItemRequestSchema;
    output: typeof GetItemResponseSchema;
  },
  /**
   * @generated from rpc item.v1.ItemService.ListItems
   */
  listItems: {
    methodKind: "unary";
    input: typeof ListItemsRequestSchema;
    output: typeof ListItemsResponseSchema;
  },
  /**
   * @generated from rpc item.v1.ItemService.UpdateItem
   */
  updateItem: {
    methodKind: "unary";
    input: typeof UpdateItemRequestSchema;
    output: typeof UpdateItemResponseSchema;
  },
  /**
   * @generated from rpc item.v1.ItemService.DeleteItem
   */
  deleteItem: {
    methodKind: "unary";
    input: typeof DeleteItemRequestSchema;
    output: typeof DeleteItemResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_item_v1_item, 0);

