// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file item/v1/item.proto (package item.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file item/v1/item.proto.
 */
export const file_item_v1_item: GenFile = /*@__PURE__*/
  fileDesc("ChJpdGVtL3YxL2l0ZW0ucHJvdG8SB2l0ZW0udjEiugEKBEl0ZW0SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIjCgZzdGF0dXMYBiABKA4yEy5pdGVtLnYxLkl0ZW1TdGF0dXMqiwEKCkl0ZW1TdGF0dXMSGwoXSVRFTV9TVEFUVVNfVU5TUEVDSUZJRUQQABIVChFJVEVNX1NUQVRVU19EUkFGVBABEhYKEklURU1fU1RBVFVTX0FDVElWRRACEhgKFElURU1fU1RBVFVTX0FSQ0hJVkVEEAMSFwoTSVRFTV9TVEFUVVNfREVMRVRFRBAEQoEBCgtjb20uaXRlbS52MUIJSXRlbVByb3RvUAFaKmdycGMtc2VydmVyL3Byb3RvLWdlbmVyYXRlZC9pdGVtL3YxO2l0ZW12MaICA0lYWKoCB0l0ZW0uVjHKAgdJdGVtXFYx4gITSXRlbVxWMVxHUEJNZXRhZGF0YeoCCEl0ZW06OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message item.v1.Item
 */
export type Item = Message<"item.v1.Item"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: item.v1.ItemStatus status = 6;
   */
  status: ItemStatus;
};

/**
 * Describes the message item.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema: GenMessage<Item> = /*@__PURE__*/
  messageDesc(file_item_v1_item, 0);

/**
 * @generated from enum item.v1.ItemStatus
 */
export enum ItemStatus {
  /**
   * @generated from enum value: ITEM_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ITEM_STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * @generated from enum value: ITEM_STATUS_ACTIVE = 2;
   */
  ACTIVE = 2,

  /**
   * @generated from enum value: ITEM_STATUS_ARCHIVED = 3;
   */
  ARCHIVED = 3,

  /**
   * @generated from enum value: ITEM_STATUS_DELETED = 4;
   */
  DELETED = 4,
}

/**
 * Describes the enum item.v1.ItemStatus.
 */
export const ItemStatusSchema: GenEnum<ItemStatus> = /*@__PURE__*/
  enumDesc(file_item_v1_item, 0);

