// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file item/v1/item_service.proto (package item.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { CreateItemRequestSchema, CreateItemResponseSchema, DeleteItemRequestSchema, DeleteItemResponseSchema, GetItemRequestSchema, GetItemResponseSchema, ListItemsRequestSchema, ListItemsResponseSchema, UpdateItemRequestSchema, UpdateItemResponseSchema, WatchItemsRequestSchema, WatchItemsResponseSchema } from "./item_pb";
import { file_item_v1_item } from "./item_pb";

/**
 * Describes the file item/v1/item_service.proto.
 */
export const file_item_v1_item_service: GenFile = /*@__PURE__*/
  fileDesc("ChppdGVtL3YxL2l0ZW1fc2VydmljZS5wcm90bxIHaXRlbS52MTK5AwoLSXRlbVNlcnZpY2USRwoKQ3JlYXRlSXRlbRIaLml0ZW0udjEuQ3JlYXRlSXRlbVJlcXVlc3QaGy5pdGVtLnYxLkNyZWF0ZUl0ZW1SZXNwb25zZSIAEj4KB0dldEl0ZW0SFy5pdGVtLnYxLkdldEl0ZW1SZXF1ZXN0GhguaXRlbS52MS5HZXRJdGVtUmVzcG9uc2UiABJECglMaXN0SXRlbXMSGS5pdGVtLnYxLkxpc3RJdGVtc1JlcXVlc3QaGi5pdGVtLnYxLkxpc3RJdGVtc1Jlc3BvbnNlIgASRwoKVXBkYXRlSXRlbRIaLml0ZW0udjEuVXBkYXRlSXRlbVJlcXVlc3QaGy5pdGVtLnYxLlVwZGF0ZUl0ZW1SZXNwb25zZSIAEkcKCkRlbGV0ZUl0ZW0SGi5pdGVtLnYxLkRlbGV0ZUl0ZW1SZXF1ZXN0GhsuaXRlbS52MS5EZWxldGVJdGVtUmVzcG9uc2UiABJJCgpXYXRjaEl0ZW1zEhouaXRlbS52MS5XYXRjaEl0ZW1zUmVxdWVzdBobLml0ZW0udjEuV2F0Y2hJdGVtc1Jlc3BvbnNlIgAwAUKeAQoLY29tLml0ZW0udjFCEEl0ZW1TZXJ2aWNlUHJvdG9QAVpAZ2l0aHViLmNvbS9oZW9qZW9uZ2JvL2dycGMvc2VydmVyL3Byb3RvLWdlbmVyYXRlZC9pdGVtL3YxO2l0ZW12MaICA0lYWKoCB0l0ZW0uVjHKAgdJdGVtXFYx4gITSXRlbVxWMVxHUEJNZXRhZGF0YeoCCEl0ZW06OlYxYgZwcm90bzM", [file_item_v1_item]);

/**
 * ItemService provides CRUD operations for items
 *
 * @generated from service item.v1.ItemService
 */
export const ItemService: GenService<{
  /**
   * @generated from rpc item.v1.ItemService.CreateItem
   */
  createItem: {
    methodKind: "unary";
    input: typeof CreateItemRequestSchema;
    output: typeof CreateItemResponseSchema;
  },
  /**
   * @generated from rpc item.v1.ItemService.GetItem
   */
  getItem: {
    methodKind: "unary";
    input: typeof GetItemRequestSchema;
    output: typeof GetItemResponseSchema;
  },
  /**
   * @generated from rpc item.v1.ItemService.ListItems
   */
  listItems: {
    methodKind: "unary";
    input: typeof ListItemsRequestSchema;
    output: typeof ListItemsResponseSchema;
  },
  /**
   * @generated from rpc item.v1.ItemService.UpdateItem
   */
  updateItem: {
    methodKind: "unary";
    input: typeof UpdateItemRequestSchema;
    output: typeof UpdateItemResponseSchema;
  },
  /**
   * @generated from rpc item.v1.ItemService.DeleteItem
   */
  deleteItem: {
    methodKind: "unary";
    input: typeof DeleteItemRequestSchema;
    output: typeof DeleteItemResponseSchema;
  },
  /**
   * Server streaming: Watch item changes in real-time
   *
   * @generated from rpc item.v1.ItemService.WatchItems
   */
  watchItems: {
    methodKind: "server_streaming";
    input: typeof WatchItemsRequestSchema;
    output: typeof WatchItemsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_item_v1_item_service, 0);

