// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts,import_extension=none"
// @generated from file item/v1/item_service.proto (package item.v1, syntax proto3)
/* eslint-disable */

import { ItemService } from "./item_service_pb";

/**
 * @generated from rpc item.v1.ItemService.CreateItem
 */
export const createItem = ItemService.method.createItem;

/**
 * @generated from rpc item.v1.ItemService.GetItem
 */
export const getItem = ItemService.method.getItem;

/**
 * @generated from rpc item.v1.ItemService.ListItems
 */
export const listItems = ItemService.method.listItems;

/**
 * @generated from rpc item.v1.ItemService.UpdateItem
 */
export const updateItem = ItemService.method.updateItem;

/**
 * @generated from rpc item.v1.ItemService.DeleteItem
 */
export const deleteItem = ItemService.method.deleteItem;
