// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=none"
// @generated from file item/item_service.proto (package item, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateItemRequest, CreateItemResponse, DeleteItemRequest, DeleteItemResponse, GetItemRequest, GetItemResponse, ListItemsRequest, ListItemsResponse, UpdateItemRequest, UpdateItemResponse, WatchItemsRequest, WatchItemsResponse } from "./item_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service item.ItemService
 */
export const ItemService = {
  typeName: "item.ItemService",
  methods: {
    /**
     * @generated from rpc item.ItemService.CreateItem
     */
    createItem: {
      name: "CreateItem",
      I: CreateItemRequest,
      O: CreateItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc item.ItemService.GetItem
     */
    getItem: {
      name: "GetItem",
      I: GetItemRequest,
      O: GetItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc item.ItemService.ListItems
     */
    listItems: {
      name: "ListItems",
      I: ListItemsRequest,
      O: ListItemsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc item.ItemService.UpdateItem
     */
    updateItem: {
      name: "UpdateItem",
      I: UpdateItemRequest,
      O: UpdateItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc item.ItemService.DeleteItem
     */
    deleteItem: {
      name: "DeleteItem",
      I: DeleteItemRequest,
      O: DeleteItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc item.ItemService.WatchItems
     */
    watchItems: {
      name: "WatchItems",
      I: WatchItemsRequest,
      O: WatchItemsResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

