// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file item/item.proto (package item, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file item/item.proto.
 */
export const file_item_item: GenFile = /*@__PURE__*/
  fileDesc("Cg9pdGVtL2l0ZW0ucHJvdG8SBGl0ZW0iyAEKBEl0ZW0SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIgCgZzdGF0dXMYBiABKA4yEC5pdGVtLkl0ZW1TdGF0dXMSDwoHdXNlcl9pZBgHIAEoCSqLAQoKSXRlbVN0YXR1cxIbChdJVEVNX1NUQVRVU19VTlNQRUNJRklFRBAAEhUKEUlURU1fU1RBVFVTX0RSQUZUEAESFgoSSVRFTV9TVEFUVVNfQUNUSVZFEAISGAoUSVRFTV9TVEFUVVNfQVJDSElWRUQQAxIXChNJVEVNX1NUQVRVU19ERUxFVEVEEARCZwoIY29tLml0ZW1CCUl0ZW1Qcm90b1ABWiBncnBjLXNlcnZlci9wcm90by1nZW5lcmF0ZWQvaXRlbaICA0lYWKoCBEl0ZW3KAgRJdGVt4gIQSXRlbVxHUEJNZXRhZGF0YeoCBEl0ZW1iBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message item.Item
 */
export type Item = Message<"item.Item"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: item.ItemStatus status = 6;
   */
  status: ItemStatus;

  /**
   * @generated from field: string user_id = 7;
   */
  userId: string;
};

/**
 * Describes the message item.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema: GenMessage<Item> = /*@__PURE__*/
  messageDesc(file_item_item, 0);

/**
 * @generated from enum item.ItemStatus
 */
export enum ItemStatus {
  /**
   * @generated from enum value: ITEM_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ITEM_STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * @generated from enum value: ITEM_STATUS_ACTIVE = 2;
   */
  ACTIVE = 2,

  /**
   * @generated from enum value: ITEM_STATUS_ARCHIVED = 3;
   */
  ARCHIVED = 3,

  /**
   * @generated from enum value: ITEM_STATUS_DELETED = 4;
   */
  DELETED = 4,
}

/**
 * Describes the enum item.ItemStatus.
 */
export const ItemStatusSchema: GenEnum<ItemStatus> = /*@__PURE__*/
  enumDesc(file_item_item, 0);

